flaskapp/app/__init__.py
from flask import Flask
from flask_cors import CORS
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

from app import blueprints
from config import Config

db = SQLAlchemy()
login = LoginManager()

def create_app(config_class=Config):
	app = Flask(__name__, template_folder='../templates', static_folder='../static')
	app.config.from_object(config_class)

	db.init_app(app)
	login.init_app(app)
	login.login_view = 'login'

	# Register all Blueprints
	blueprints.register_blueprints(app)

	CORS(app)
	return app

app = create_app()
from . import common_routes

@app.shell_context_processor
def make_shell_context():
	return {'db': db}

flaskapp/app/blueprints/__init__.py
def register_blueprints(app):
	# Content Blueprint Register
	from .search import search
	app.register_blueprint(search)


	# User Blueprint Register
	from .user import user
	app.register_blueprint(user)

flaskapp/app/blueprints/search/__init__.py
# DECLARATE BLUEPRINT
from flask import Blueprint
search = Blueprint('search', __name__, template_folder='templates', url_prefix='/search')

from . import api
from . import routes

flaskapp/app/blueprints/search/routes.py
from app.decorators.templated import templated
from . import search


@search.route('/manual')
@templated('manual/index.html')
def search_manual():
	return dict(subtitle='Manual Search', filters={})

flaskapp/app/blueprints/user/__init__.py
# DECLARATE BLUEPRINT
from flask import Blueprint
user = Blueprint('user', __name__, template_folder='templates', url_prefix='/user')

from . import api
from . import routes

flaskapp/app/blueprints/user/routes.py
from app.blueprints.user.services.svc import UserServices
from app.decorators.templated import templated
from . import user


@user.route('/crud')
@templated('crud/index.html')
def user_crud_pages():
	users = UserServices().get_all_users()
	return dict(
		subtitle='Admin - User',
		users=users
	)

flaskapp/main.py
import os

from app import app

if __name__ == '__main__':
    # This is used when running locally only.
    app.run(host='127.0.0.1', port=8082, debug=False)

flaskapp/templates/base_tmpl.html
<!DOCTYPE html>
<html lang="en">
    <!--<![endif]-->
    <!-- BEGIN HEAD -->
    <head>
        <title> App | {{subtitle}}</title>
        {% block pageLevelCss %}{% endblock %}
        {% include "common/__head_common.html" %}
    </head>
    <!-- END HEAD -->

    <body>
        <div class="wrapper">
         <div class="sidebar" data-color="purple" data-background-color="white" data-image="../assets/img/sidebar-1.jpg">
            {% block menu %}
                {% include "common/__menu.html" %}
            {% endblock %}
        </div>

        <div class="main-panel">
            {% block header %}
                {% include "common/__header.html" %}
            {% endblock %}

            <div class="content">
                <div class="cotainenr-fluid">
                    {% block main_content %}{% endblock %}
                </div>
            </div>

            <footer class="footer">
                {% include "common/__footer.html" %}
            </footer>

        </div>

        {% block pageLevelPlugins %}{% endblock %}
        {% block pageLevelJs %}{% endblock %}
        {% include "common/__common_js.html" %}
    </body>
</html>

flaskapp/templates/common/__common_js.html
<script src="/static/plugins/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/plugins/bootstrap-select/bootstrap-select.min.js"></script>
<script src="/static/plugins/chartist.min.js"></script>

flaskapp/templates/common/__footer.html
<div class="container-fluid">
    <div class="copyright float-right">
        ©
        <script>
            document.write(new Date().getFullYear())
        </script>
        made with <i class="material-icons">favorite</i> by Maria Victoria Mora Navarrete 2021
    </div>
</div>

flaskapp/templates/common/__head_common.html
<meta charset="utf-8">
<meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />

<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
<link href="/static/css/template/material-dashboard.css?v=2.1.2" rel="stylesheet" />
<link href="/static/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" />

<!-- BEGIN FAVICON -->
<link rel="shortcut icon" href="/static/assets/favicon.ico" />
<!-- END FAVICON -->

flaskapp/templates/common/__header.html
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            <a class="navbar-brand">
                {% block title %} {% endblock %}
            </a>
        </div>

        <div class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">person</i>
                        <p class="d-lg-none d-md-block">
                            Account
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                        <a class="dropdown-item" href="#">Profile</a>
                        <a class="dropdown-item" href="#">Settings</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Log out</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

flaskapp/templates/common/__menu.html
<div class="sidebar-wrapper">

    <div class="logo"><a href="http://www.creative-tim.com" class="simple-text logo-normal">
        Creative Tim
    </a></div>
    <ul class="nav">
        <li class="nav-item {{ "active" if url_for('search.search_manual') == request.path or url_for('search.launch_search') == request.path }}">
            <a class="nav-link" href="{{ url_for('search.search_manual') }}">
                <i class="material-icons">search</i>
                <p>Search</p>
            </a>
        </li>

        <li class="nav-item {{ "active" if url_for('user.user_crud_pages') == request.path }}">
            <a class="nav-link" href="{{ url_for('user.user_crud_pages') }}">
                <i class="material-icons">settings</i>
                <p> Admin</p>
            </a>
        </li>
    </ul>
</div>

flaskapp/templates/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />

    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/login.css">
    <link rel="stylesheet" type="text/css" href="/static/css/util.css">

    <!-- BEGIN FAVICON -->
    <link rel="shortcut icon" href="/static/assets/favicon.ico" />
    <!-- END FAVICON -->
</head>

<body>

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login101 p-l-50 p-r-50 p-t-77 p-b-30">
            <form action="{{ url_for("sing_in") }}" method="post">
                <span class="login100-form-title p-b-55"> LOGIN</span>

                {% if error %}
                    <div style="width:100%" class="alert alert-danger alert-dismissible fade show" role="alert">
                        <p><strong>Error:</strong> {{ error }}>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </p>
                    </div>
                {% endif %}

                <br>

                <div class="wrap-input100 validate-input m-b-16" data-validate = "Valid email is required: ex@abc.xyz">
                    <input class="input101" type="text" id="username" name="username" placeholder="Enter user">
                    <span class="focus-input101"></span>
                    <span class="symbol-input100">
							<span class="lnr lnr-user"></span>
						</span>
                </div>

                <div class="wrap-input100 validate-input m-b-16" data-validate = "Password is required">
                    <input class="input101" type="password" id="password" name="password" placeholder="Enter password">
                    <span class="focus-input101"></span>
                    <span class="symbol-input100">
							<span class="lnr lnr-lock"></span>
						</span>
                </div>
                <input type="submit" class="login100-form-btn">

                <div class="text-center w-full p-t-115">
						<span class="txt1">
							Not a member?
						</span>

                    <a class="txt1 bo1 hov1" href="{{ url_for("register") }}">
                        Sign up now
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>

</body>
</html>

flaskapp/templates/register/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/login.css">
    <link rel="stylesheet" type="text/css" href="/static/css/util.css">

    <!-- BEGIN FAVICON -->
    <link rel="shortcut icon" href="/static/assets/favicon.ico" />
    <!-- END FAVICON -->

</head>
<body>

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-l-50 p-r-50 p-t-77 p-b-30">
            <form class="login100-form validate-form" action="{{ url_for("user.new", redirect="/index") }}" method="post">
                <span class="login100-form-title p-b-55"> REGISTERED</span>

                {% with success = get_flashed_messages(category_filter=["success"]) %}
                    {% if success %}
                        {%- for message in success %}
                            <div style="width:100%" class="alert alert-success alert-dismissible fade show" role="alert">
                                <span>{{ message }} <a href="{{url_for('index')}}">return home</a> </span>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor -%}
                    {% endif %}
                {% endwith %}

                {% with error = get_flashed_messages(category_filter=["error"]) %}
                    {% if error %}
                        {%- for message in error %}
                            <div style="width:100%" class="error alert alert-danger alert-dismissible fade show" role="alert">
                                <p><strong>Error:</strong> {{ message }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </p>
                            </div>
                        {% endfor -%}
                    {% endif %}
                {% endwith %}

                <label class="label-input100">Your Name *</label>
                <div class="wrap-input100 rs1 m-b-16">
                    <input class="input100" type="text" name="name" placeholder="Enter your name">
                    <span class="focus-input100"></span>
                </div>
                <div class="wrap-input100 rs1 m-b-16">
                    <input class="input100" type="text" name="lastname" placeholder="Enter your last name">
                    <span class="focus-input100"></span>
                </div>

                <label class="label-input100">Telephone *</label>

                <div class="wrap-input100 m-b-16">
                    <input class="input100" type="number" name="phone" placeholder="Enter your telephone">
                    <span class="focus-input100"></span>
                </div>

                <label class="label-input100">Date of birth *</label>

                <div class="wrap-input100 m-b-16">
                    <input class="input100" type="date" name="birth_date" placeholder="Enter your birthdate">
                    <span class="focus-input100"></span>
                </div>

                <label class="label-input100">Salary *</label>

                <div class="wrap-input100 m-b-16">
                    <input class="input100" type="number" name="salary" placeholder="Enter your salary">
                    <span class="focus-input100"></span>
                </div>

                <label class="label-input100">User *</label>
                <div class="wrap-input100 m-b-16">
                    <input class="input100" type="text" name="username" placeholder="Enter user">
                    <span class="focus-input100"></span>
                </div>

                <label class="label-input100">Password *</label>
                <div class="wrap-input100 validate-input m-b-16" data-validate = "Password is required">
                    <input class="input100" type="password" name="password" placeholder="Enter password">
                    <span class="focus-input100"></span>
                </div>
                <div class="container-login100-form-btn p-t-25">
                    <button class="login100-form-btn">
                        REGISTERED
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

</body>
</html>